### PR TITLE
Update to 5.12 runtime

### PR DESCRIPTION
**Pull request by nedrichards**

### CODE REVIEW

**Comment by nedrichards** [comment]
testbot, build

**Comment by petitlapin** [comment]
hi, there has been some regression due to Qt5.12 that has been fixed after 0.95.
Is it possible to wait next release (next week) which contains the fixes for Qt5.12 to update both version?

**Comment by petitlapin** [comment]
https://phabricator.kde.org/T10195 for the issues

**Comment by nedrichards** [comment]
Of course!

**Comment by nedrichards** [comment]
@petitlapin from my perspective this was partly about using/testing the new autobuilder/temporary repo stuff - glad there's fixes incoming though!

**Comment by eszlari** [comment]
done: https://github.com/flathub/org.kde.gcompris/commit/85173ffdfd530b8a92ead8a9353e46775b290da1

**Pull request closed without merging**
